import { Category, Listing, User, Location } from '../types';

export const mockUsers: User[] = [
  {
    uid: '1',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john@example.com',
    phone: '+61 400 123 456',
    location: 'Sydney, NSW',
    profileImage: 'https://via.placeholder.com/100',
    isVerified: true,
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-01-15'),
    listings: [],
    favorites: [],
    conversations: [],
    notificationSettings: {
      messages: true,
      favorites: true,
      newListings: true,
      priceChanges: true,
      system: true,
    },
  },
  {
    uid: '2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah@example.com',
    phone: '+61 400 789 012',
    location: 'Melbourne, VIC',
    profileImage: 'https://via.placeholder.com/100',
    isVerified: true,
    createdAt: new Date('2022-11-20'),
    updatedAt: new Date('2022-11-20'),
    listings: [],
    favorites: [],
    conversations: [],
    notificationSettings: {
      messages: true,
      favorites: true,
      newListings: true,
      priceChanges: true,
      system: true,
    },
  },
  {
    uid: '3',
    firstName: 'Mike',
    lastName: 'Wilson',
    email: 'mike@example.com',
    phone: '+61 400 345 678',
    location: 'Brisbane, QLD',
    profileImage: 'https://via.placeholder.com/100',
    isVerified: true,
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date('2023-03-10'),
    listings: [],
    favorites: [],
    conversations: [],
    notificationSettings: {
      messages: true,
      favorites: true,
      newListings: true,
      priceChanges: true,
      system: true,
    },
  },
];

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Real Estate',
    icon: 'home',
    color: '#4CAF50',
    subcategories: [
      { id: '1-1', name: 'Houses for Sale', icon: 'home' },
      { id: '1-2', name: 'Apartments for Sale', icon: 'business' },
      { id: '1-3', name: 'Houses for Rent', icon: 'home-outline' },
      { id: '1-4', name: 'Apartments for Rent', icon: 'business-outline' },
      { id: '1-5', name: 'Land', icon: 'map' },
    ],
  },
  {
    id: '2',
    name: 'Vehicles',
    icon: 'car',
    color: '#2196F3',
    subcategories: [
      { id: '2-1', name: 'Cars', icon: 'car' },
      { id: '2-2', name: 'Motorcycles', icon: 'bicycle' },
      { id: '2-3', name: 'Trucks', icon: 'car-sport' },
      { id: '2-4', name: 'Boats', icon: 'boat' },
      { id: '2-5', name: 'Caravans', icon: 'home' },
    ],
  },
  {
    id: '3',
    name: 'Electronics',
    icon: 'phone-portrait',
    color: '#FF9800',
    subcategories: [
      { id: '3-1', name: 'Mobile Phones', icon: 'phone-portrait' },
      { id: '3-2', name: 'Computers', icon: 'laptop' },
      { id: '3-3', name: 'TVs & Audio', icon: 'tv' },
      { id: '3-4', name: 'Cameras', icon: 'camera' },
      { id: '3-5', name: 'Gaming', icon: 'game-controller' },
    ],
  },
  {
    id: '4',
    name: 'Fashion',
    icon: 'shirt',
    color: '#E91E63',
    subcategories: [
      { id: '4-1', name: 'Men\'s Clothing', icon: 'man' },
      { id: '4-2', name: 'Women\'s Clothing', icon: 'woman' },
      { id: '4-3', name: 'Kids\' Clothing', icon: 'people' },
      { id: '4-4', name: 'Shoes', icon: 'footsteps' },
      { id: '4-5', name: 'Accessories', icon: 'watch' },
    ],
  },
  {
    id: '5',
    name: 'Home & Garden',
    icon: 'leaf',
    color: '#8BC34A',
    subcategories: [
      { id: '5-1', name: 'Furniture', icon: 'bed' },
      { id: '5-2', name: 'Garden Tools', icon: 'leaf' },
      { id: '5-3', name: 'Kitchen Appliances', icon: 'restaurant' },
      { id: '5-4', name: 'Decor', icon: 'color-palette' },
      { id: '5-5', name: 'DIY Tools', icon: 'hammer' },
    ],
  },
  {
    id: '6',
    name: 'Sports & Leisure',
    icon: 'football',
    color: '#FF5722',
    subcategories: [
      { id: '6-1', name: 'Fitness Equipment', icon: 'fitness' },
      { id: '6-2', name: 'Bicycles', icon: 'bicycle' },
      { id: '6-3', name: 'Camping Gear', icon: 'camp' },
      { id: '6-4', name: 'Water Sports', icon: 'water' },
      { id: '6-5', name: 'Team Sports', icon: 'football' },
    ],
  },
];

export const mockListings: Listing[] = [
  {
    id: '1',
    title: 'Modern 3-Bedroom House in Sydney',
    description: 'Beautiful family home with modern amenities, large backyard, and excellent location near schools and transport.',
    price: 850000,
    currency: 'AUD',
    category: 'Real Estate',
    subcategory: 'Houses for Sale',
    location: 'Sydney, NSW',
    images: [
      'https://via.placeholder.com/400x300/4CAF50/FFFFFF?text=House+1',
      'https://via.placeholder.com/400x300/4CAF50/FFFFFF?text=House+2',
    ],
    userId: '1',
    user: mockUsers[0],
    condition: 'new',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    status: 'active',
    views: 245,
    favorites: 18,
    tags: ['family', 'modern', 'backyard', 'schools'],
  },
  {
    id: '2',
    title: '2019 Toyota Camry - Excellent Condition',
    description: 'Well-maintained Toyota Camry with low mileage, full service history, and great fuel efficiency.',
    price: 28000,
    currency: 'AUD',
    category: 'Vehicles',
    subcategory: 'Cars',
    location: 'Melbourne, VIC',
    images: [
      'https://via.placeholder.com/400x300/2196F3/FFFFFF?text=Car+1',
      'https://via.placeholder.com/400x300/2196F3/FFFFFF?text=Car+2',
    ],
    userId: '2',
    user: mockUsers[1],
    condition: 'good',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    status: 'active',
    views: 189,
    favorites: 12,
    tags: ['toyota', 'camry', 'low-mileage', 'fuel-efficient'],
  },
  {
    id: '3',
    title: 'iPhone 14 Pro - 128GB - Space Black',
    description: 'Like new iPhone 14 Pro, purchased 6 months ago, comes with original box and accessories.',
    price: 1200,
    currency: 'AUD',
    category: 'Electronics',
    subcategory: 'Mobile Phones',
    location: 'Brisbane, QLD',
    images: [
      'https://via.placeholder.com/400x300/FF9800/FFFFFF?text=iPhone+1',
      'https://via.placeholder.com/400x300/FF9800/FFFFFF?text=iPhone+2',
    ],
    userId: '3',
    user: mockUsers[2],
    condition: 'like-new',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    status: 'active',
    views: 156,
    favorites: 8,
    tags: ['iphone', '14-pro', '128gb', 'space-black'],
  },
  {
    id: '4',
    title: 'Vintage Leather Jacket - Size M',
    description: 'Authentic vintage leather jacket in excellent condition, perfect for motorcycle enthusiasts.',
    price: 350,
    currency: 'AUD',
    category: 'Fashion',
    subcategory: 'Men\'s Clothing',
    location: 'Sydney, NSW',
    images: [
      'https://via.placeholder.com/400x300/E91E63/FFFFFF?text=Jacket+1',
    ],
    userId: '1',
    user: mockUsers[0],
    condition: 'good',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
    status: 'active',
    views: 98,
    favorites: 5,
    tags: ['vintage', 'leather', 'motorcycle', 'size-m'],
  },
  {
    id: '5',
    title: 'Professional Gym Equipment Set',
    description: 'Complete home gym setup including bench press, weights, and cardio equipment.',
    price: 2500,
    currency: 'AUD',
    category: 'Sports & Leisure',
    subcategory: 'Fitness Equipment',
    location: 'Melbourne, VIC',
    images: [
      'https://via.placeholder.com/400x300/FF5722/FFFFFF?text=Gym+1',
      'https://via.placeholder.com/400x300/FF5722/FFFFFF?text=Gym+2',
    ],
    userId: '2',
    user: mockUsers[1],
    condition: 'good',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    status: 'active',
    views: 203,
    favorites: 15,
    tags: ['gym', 'fitness', 'home-gym', 'weights'],
  },
];

export const mockLocations: Location[] = [
  { id: '1', name: 'Sydney', state: 'NSW', country: 'Australia' },
  { id: '2', name: 'Melbourne', state: 'VIC', country: 'Australia' },
  { id: '3', name: 'Brisbane', state: 'QLD', country: 'Australia' },
  { id: '4', name: 'Perth', state: 'WA', country: 'Australia' },
  { id: '5', name: 'Adelaide', state: 'SA', country: 'Australia' },
  { id: '6', name: 'Canberra', state: 'ACT', country: 'Australia' },
  { id: '7', name: 'Darwin', state: 'NT', country: 'Australia' },
  { id: '8', name: 'Hobart', state: 'TAS', country: 'Australia' },
];
